### ISSUE TITLE
Uninitialized variable (typo)

### ISSUE THREAD

**Issue by noproto** [maaaaz/jnianalyzer#1]
Python traceback:
Traceback (most recent call last):
  File "/home/noproto/Downloads/jnianalyzer-master/jnianalyzer.py", line 295, in <module>
    main(options, arguments)
  File "/home/noproto/Downloads/jnianalyzer-master/jnianalyzer.py", line 283, in main
    arm_analysis()
  File "/home/noproto/Downloads/jnianalyzer-master/jnianalyzer.py", line 271, in arm_analysis
    line += '\t\t;jnicall: ' + regs[reg]
KeyError: 'r3'

Fix: Rename reg to reg1
https://github.com/noproto/jnianalyzer/commit/207206dfdd4fea082b597b05149c13edeed8945a

**Comment by maaaaz** [comment]
Hello @noproto,

Thank you that's a good catch, I even wonder how no one ever encountered such bug.
That's now fixed.

Cheers !
